net/web/permission/WinStudio.Permission.Web/Models/AccountModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;

namespace WinStudio.Permission.Web.Models
{
    public class LocalPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "当前密码")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "{0} 必须至少包含 {2} 个字符。", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "新密码")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "确认新密码")]
        [Compare("NewPassword", ErrorMessage = "新密码和确认密码不匹配。")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginModel
    {
        [Required]
        [Display(Name = "用户名")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }

        [Display(Name = "记住我?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterModel
    {
        [Required]
        [Display(Name = "用户名")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "{0} 必须至少包含 {2} 个字符。", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "确认密码")]
        [Compare("Password", ErrorMessage = "密码和确认密码不匹配。")]
        public string ConfirmPassword { get; set; }
    }

    public class ExternalLogin
    {
        public string Provider { get; set; }
        public string ProviderDisplayName { get; set; }
        public string ProviderUserId { get; set; }
    }
}

net/web/permission/WinStudio.Permission.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WinStudio.Permission.Models;

namespace WinStudio.Permission.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //if (null == HttpContext.Application[MvcApplication.PermissionSysConfig])
            //    return RedirectToAction("About", new { reason = "系统未启动。", opentime = DateTime.Now.AddHours(3) });

            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";


            return View();
        }

        public ActionResult About(string reason, DateTime opentime)
        {
            ViewBag.Message = string.IsNullOrEmpty(reason) ? "系统暂时停止服务。" : reason;
            ViewBag.OpenTime = opentime.ToString("yyyy-MM-dd HH:MM");

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

net/web/permission/WinStudio.Permission.Web/Controllers/ManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web.Mvc;
using WinStudio.Permission.BusiServices.Interfaces;
using WinStudio.Permission.Common.Framework.Abstract;
using WinStudio.Permission.Common.Framework.Attributes;
using WinStudio.Permission.Models;

namespace WinStudio.Permission.Web.Controllers
{
    [NeedPermissionAdmin]
    public class ManagementController : AbstractPermissionMvcController
    {
        ISysModuleBusiService ibsSubSystem;
        IRoleBusiService ibsRole;
        IFunctionBusiService ibsFunction;
        ICustomerBusiService ibsCustomer;
        public ManagementController(
            ISysModuleBusiService bsSubSystem,
            IRoleBusiService bsRole,
            IFunctionBusiService bsFunction,
        ICustomerBusiService bsCustomer)
        {
            ibsSubSystem = bsSubSystem;
            ibsRole = bsRole;
            ibsFunction = bsFunction;
            ibsCustomer = bsCustomer;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SysModule(int id = 0)
        {
            return View();
        }
        [HttpPost]
        public ActionResult SysModuleEdit(SysModule module)
        {
            return View();
        }
        public ActionResult Role(int id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult RoleEdit(Role role)
        {
            return View();
        }
        public ActionResult Function(int id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult FunctionEdit(Function function)
        {
            return View();
        }
        public ActionResult Customer(int id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult CustomerEdit(Customer customer)
        {
            return View();
        }
    }
}

net/web/permission/WinStudio.Permission.Web/Views/Admin/Index.cshtml
@model WinStudio.Permission.Models.SysConfig

@{
    ViewBag.Title = "权限系统配置";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>SysConfig</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.UseWebConfig)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.UseWebConfig)
            @Html.ValidationMessageFor(model => model.UseWebConfig)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.WebConfigConnectionName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.WebConfigConnectionName)
            @Html.ValidationMessageFor(model => model.WebConfigConnectionName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DbServer)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DbServer)
            @Html.ValidationMessageFor(model => model.DbServer)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DbName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DbName)
            @Html.ValidationMessageFor(model => model.DbName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DbUser)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DbUser)
            @Html.ValidationMessageFor(model => model.DbUser)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DbPwd)
        </div>
        <div class="editor-field">
            @Html.PasswordFor(model => model.DbPwd)
            @Html.ValidationMessageFor(model => model.DbPwd)
        </div>

        <p>
            <input type="submit" value="Submit" />
        </p>
    </fieldset>
}

net/web/permission/WinStudio.Permission.Web/Views/Admin/Run.cshtml
@{
    ViewBag.Title = "Run";
}

<h2>Run</h2>

net/web/permission/WinStudio.Permission.Web/Views/Exception/Index.cshtml
@{
    ViewBag.Title = "错误页面";
}

<h2>您的访问出现错误！</h2>
<div>@Html.Raw(TempData["Exception"])</div>

net/web/permission/WinStudio.Permission.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>重要提示：</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>

    <p>
        预计开放时间为：@ViewBag.OpenTime
    </p>

    <p>
        给您带来的不便敬请谅解，如有紧急需要，请联系管理员。
    </p>
</article>

net/web/permission/WinStudio.Permission.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

net/web/permission/WinStudio.Permission.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

net/web/permission/WinStudio.Permission.Web/Views/Management/AutoInit.cshtml
@model WinStudio.Permission.Models.SysModule
@{
    ViewBag.Title = "AutoInit";
    Layout = null;
}
<h2>初始化功能点</h2>
@using (Html.BeginForm("DoAutoInit", "Management", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Function</legend>

        <div class="editor-label">
            模块： @Html.DisplayFor(model => model.Name)
        </div>
        <div class="editor-field">
        </div>
        <div class="editor-label">
            域名称
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Code)
        </div>

        <div class="editor-label">
            功能点文件
        </div>
        <div class="editor-field">
            <input type="file" id="filePermissionUploader" name="PermissionFile" accept="dll" />
        </div>
        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.Code)
        <p>
            <input type="submit" value="Save" />
            @Html.ValidationSummary(true)
            提示：该操作将覆盖该模块下原有的权限点，并会移除原有的权限关系。
        </p>
    </fieldset>
}

<script>
    $(document).ready(function () {
        $("#SubSystem").die().live("change", function () {
            $("#tbFunctionArea").val($(this).val());
        })
    })

</script>

net/web/permission/WinStudio.Permission.Web/Views/Management/Customer.cshtml
@model IEnumerable<WinStudio.Permission.Models.Customer>

@{
    ViewBag.Title = "Customer";
}

<h2>Customer</h2>

<p>
    @Html.ActionLink("Create New", "CustomerEdit", new { mid = ViewBag.ModuleID })
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Account)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsUsing)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Memo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Display)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Account)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsUsing)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Display)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedTime)
            </td>
            <td>
                @Html.ActionLink("Edit", "CustomerEdit", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

net/web/permission/WinStudio.Permission.Web/Views/Management/CustomerEdit.cshtml
@model WinStudio.Permission.Models.Customer

@{
    ViewBag.Title = "CustomerEdit";
    Layout = null;
}

<h2>@(Model == null || Model.IsNewModel() ? "新建用户" : "编辑用户")</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <fieldset>
        <legend>Customer</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.Account)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Account)
            @Html.ValidationMessageFor(model => model.Account)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsUsing)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsUsing)
            @Html.ValidationMessageFor(model => model.IsUsing)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Display)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Display)
            @Html.ValidationMessageFor(model => model.Display)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Memo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Memo)
            @Html.ValidationMessageFor(model => model.Memo)
        </div>


        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.ModuleID)
        <p>
            <input type="submit" value="Save" />
            @Html.ValidationSummary(true)
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

net/web/permission/WinStudio.Permission.Web/Views/Management/Function.cshtml
@model IEnumerable<WinStudio.Permission.Models.Function>

@{
    ViewBag.Title = "Function";
}

<h2>Function</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParentID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editable)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsUsing)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Memo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Display)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editable)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsUsing)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Display)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedTime)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>

net/web/permission/WinStudio.Permission.Web/Views/Management/FunctionEdit.cshtml
@model WinStudio.Permission.Models.Function

@{
    ViewBag.Title = "FunctionEdit";
    Layout = null;
}

<h2>FunctionEdit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Function</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ParentID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ParentID)
            @Html.ValidationMessageFor(model => model.ParentID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SystemID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SystemID)
            @Html.ValidationMessageFor(model => model.SystemID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Editable)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Editable)
            @Html.ValidationMessageFor(model => model.Editable)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsUsing)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsUsing)
            @Html.ValidationMessageFor(model => model.IsUsing)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Memo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Memo)
            @Html.ValidationMessageFor(model => model.Memo)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.PID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PID)
            @Html.ValidationMessageFor(model => model.PID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.RPID)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.RPID)
            @Html.ValidationMessageFor(model => model.RPID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Display)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Display)
            @Html.ValidationMessageFor(model => model.Display)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.CreatedTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CreatedTime)
            @Html.ValidationMessageFor(model => model.CreatedTime)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ValidMsg)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ValidMsg)
            @Html.ValidationMessageFor(model => model.ValidMsg)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Deleted)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Deleted)
            @Html.ValidationMessageFor(model => model.Deleted)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

net/web/permission/WinStudio.Permission.Web/Views/Management/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = null;
}


@*<div>@Html.Action("SysModule", "Management")</div>*@

net/web/permission/WinStudio.Permission.Web/Views/Management/RoleFunctionEdit.cshtml
@model IEnumerable<WinStudio.Permission.Models.Function>

@{
    Layout = null;
}

<table>
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ParentID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsUsing)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Memo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Display)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.CheckBox("RoleFunctionChecked", ViewBag.Checked)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ParentID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsUsing)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Display)
            </td>
        </tr>
    }

</table>

net/web/permission/WinStudio.Permission.Web/Views/Management/SysModule.cshtml
@model IEnumerable<WinStudio.Permission.Models.SysModule>

@{
    ViewBag.Title = "SysModule";
    Layout = null;
}

<h2>SysModule</h2>

<p>
    @Html.ActionLink("Create New", "SysModuleEdit")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Authority)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsUsing)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Memo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Display)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedTime)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Code)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Authority)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsUsing)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Memo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Display)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedTime)
            </td>
            <td>
                @Html.ActionLink("Edit", "SysModuleEdit", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID }) |
                @Html.ActionLink("Roles", "Role", new { id = item.ID }) |
                @Html.ActionLink("Customers", "Customer", new { id = item.ID }) |
                @Html.ActionLink("Functions", "Function", new { id = item.ID })
            </td>
        </tr>
@*<tr>
            <td></td>
            <td colspan="8">@Html.Action("Role", "Management", new { id = item.ID })
            </td>
        </tr>*@
    }

</table>

net/web/permission/WinStudio.Permission.Web/Views/Managementold/AutoInit.cshtml
@{
    ViewBag.Title = "AutoInit";
}
<h2>AutoInit</h2>
<script src="~/Scripts/jquery-1.8.2.min.js"></script>
@using (Html.BeginForm("PermissionAutoInitializer", "Management", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Function</legend>

        <div class="editor-label">
            系统列表
        </div>
        <div class="editor-field">
            @Html.DropDownList("SubSystem", (SelectList)ViewBag.SubSystems, "--请选择系统--")
        </div>
        <div class="editor-label">
            域名称
        </div>
        <div class="editor-field">
            <input type="text" id="tbFunctionArea" name="FunctionArea" />
        </div>

        <div class="editor-label">
            权限文件
        </div>
        <div class="editor-field">
            <input type="file" id="filePermissionUploader" name="PermissionFile" accept="dll" />
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<script>
    $(document).ready(function () {
        $("#SubSystem").die().live("change", function () {
            $("#tbFunctionArea").val($(this).val());
        })
    })

</script>

net/web/permission/WinStudio.Permission.Web/Views/Managementold/Editor.cshtml
@{
    ViewBag.Title = "Editor";
}

<h2>Editor</h2>

net/web/permission/WinStudio.Permission.Web/Views/Managementold/RegSystemDetail.cshtml
@model WinStudio.Permission.Models.RegSystem

@{
    ViewBag.Title = "系统信息";
}

<h2> @Model.ToString()</h2>

<fieldset>
    <legend>该系统下角色</legend>
    @Html.Action("RegSystemRoleList")
</fieldset>
<fieldset>
    <legend>该系统下用户</legend>
    @Html.Action("RegSystemCustomerList")
</fieldset>
<fieldset>
    <legend>该系统下功能</legend>
    @Html.Action("RegSystemFunctionList")
</fieldset>
<p>
    @Html.ActionLink("Back to List", "RegSystemList")
</p>